### PR TITLE
Improve csv output

### PR DESCRIPTION
**Pull request by FlavBd**
Generate one csv file per exported layer and zip them for the user.

Before results.csv :
```
parcelle,,
,gid,529100
,id,14118000IB0072
,commune,14118
,prefixe,0
,section,IB
,numero,72
,contenance,36281
,created,2001-09-28
,updated,2015-03-26
,geometry,"MULTIPOLYGON ... "
,,
commune,,
,gid,245
,id,14118
,nom,CAEN
,created,2001-11-22
,updated,2018-04-19
,geometry,"MULTIPOLYGON ... "
```

After commune.csv :
```
gid;id;nom;created;updated;geometry
245;14118;CAEN;2001-11-22;2018-04-19;MULTIPOLYGON ...
302;14327;HEROUVILLE SAINT CLAIR;2002-11-28;2018-04-23;MULTIPOLYGON ...
335;14437;MONDEVILLE;2002-12-05;2016-11-17;MULTIPOLYGON ...
```

Fix https://github.com/qgis/qwc2-demo-app/issues/194

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks, I wonder whether it's better to make this an alternative format (like csv+zip), as people might already be relying on the current csv format.

**Comment by FlavBd** [comment]
Thanks for your advice. 
Like I explain in this issue : https://github.com/qgis/qwc2-demo-app/issues/198 I'm working on the possibility to choose through different format. 
Here is an idea of the result. 
image
For the moment the two possibilities are `json` and `csv` but I can add `csv + zip` like you suggest and keep the current csv format.

**Comment by FlavBd** [comment]
@manisandro what do you think about the suggestion to choose through different format and to have csv and csv + zip possibilities ? Can I continue in this way?

**Comment by manisandro** [comment]
Yes I'm ok with that, thanks.

**Comment by FlavBd** [comment]
@manisandro I made new commits about the csv export, don't hesitate to tell me if you want some modifications

**Comment by manisandro** [comment]
Thanks!

**Pull request merged**
