### PR TITLE
Store bottombar height in state

### PR DESCRIPTION
**Pull request by stamogis**
I needed the height of the bottombar for a custom plugin. Similar to the topbar, I added the storing of the bottombar height in state. Maybe this is also useful for other users.

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks! @danceb I actually completely forgot about this, this could be exactly what you need for #282?

**Comment by danceb** [comment]
@stamogis May you give me an example how to access the height of the bottombar from another plugin? I am sorry, but I have no clue how this works ...

**Comment by stamogis** [comment]
Hi @danceb, here is a small example plugin:

```JSX
import React from 'react';
import PropTypes from 'prop-types';
import {connect} from 'react-redux';

class PluginExample extends React.Component {
    static propTypes = {
        map: PropTypes.object
    };
    render() {
        const bottombarHeight = this.props.map.bottombarHeight;

        return (
            <div>...</div>
        );
    }
}

export default connect((state) => ({
    map: state.map
}), {})(PluginExample);
```

**Comment by danceb** [comment]
Thank you so much! I hope that it's ok to ask another question based on that:
How do you ensure in your plugin that the bottom bar is rendered already before request its height? I try to get the  heights of top and bottom bar for the ResizableWindow component and at the time of its rendering the bars aren't rendered yet, so I get the value `0` for their heights...

**Comment by manisandro** [comment]
Is this related to plugin activated via startup task? If yes, the solution would be to delay activating the startup task until the topbar/bottobar components are mounted - I can look into that.

**Comment by stamogis** [comment]
Sorry, I can't help here. My plugin needs to be started manually by the user via the menu and then the bars should normally already be rendered. I don't have any extra handling if the two bars aren't rendered yet.

**Comment by danceb** [comment]
> Is this related to plugin activated via startup task? If yes, the solution would be to delay activating the startup task until the topbar/bottobar components are mounted - I can look into that.

Unfortunately no. As I am trying to implement this within the ResizableWindow component, this effects all plugins which use this.

**Pull request merged**
