### PR TITLE
Improve features

### PR DESCRIPTION
**Pull request by patricev**
Hi, 
Here a pull request with some new features :
- improve qt forms  integration : 
   - read tab widget and buttons
   - read a qt linguist file for translations
   - ...
- add a style parameter in wms layers
- enable ?map in querystring 

at your disposal to discuss it
Regards

### CODE REVIEW

**Comment by manisandro** [comment]
Thansk @patricev , these look very interesting, I'll look into them as soon as time allows. In the meantime could you rebase your commits to resolve the conflict? And please also give a better commit name to `test`. Thanks!

**Comment by manisandro** [comment]
Could you please clean up your commits? Thanks

**Comment by patricev** [comment]
sorry, i'm not used with git rebase, and it's now a complete mess.... I'll clean it

**Comment by manisandro** [comment]
Unfortunately this is pretty much impossible to review, even though the contribution looks very interesting. Please clean up your commits, push one commit per feature, and don't add white-space changes to your commits. (It's a fair point that code style needs to be uniformized, but that needs to happen separately).

**Comment by manisandro** [comment]
Closing since this looks abbandoned.

**Pull request closed without merging**
