### PR TITLE
Update ShareSocials.jsx

### PR DESCRIPTION
**Pull request by claudiadragoste**
I propose to add EmailShareButton. For the future: customizing the social networks that appear.

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks - at this point it would make sense to already implement the configurability of the individual share buttons.

**Comment by claudiadragoste** [comment]
Totally agree. Do you know where I can find something similar? I think it's easy to implement, with some example I could dare to implement it. Thank you

**Comment by claudiadragoste** [comment]
Hey!! Thank you for these lines!! :) It's super nice like this.  I will think on it

**Comment by NullSeile** [comment]
We've implemented a possible solution using the proposed changes. The modification has been done in this commit: b0d6a8b0cf3b960a2ad6d98dea3d396c97705ada.

**Comment by manisandro** [comment]
Thanks! - Could you open a PR with that commit?

**Comment by manisandro** [comment]
Addressed by #203

**Pull request closed without merging**
