### PR TITLE
Add css class corresponding to map button position

### PR DESCRIPTION
**Pull request by stamogis**
For the possibility to modify certain map buttons with custom css (qwc2.css), I added another css class based on the map button position.

### CODE REVIEW

**Comment by manisandro** [comment]
Would `map-button:nth-child(n)` achieve the same without the need for extra classes?

**Comment by stamogis** [comment]
Unfortunately, this only seems to work correctly if nothing changes in the DOM. In the current demo, for example, the "Layers & Legend" button would be n = 20. If I open the measurement tool, it would be n = 21.

**Comment by manisandro** [comment]
Right, `nth-of-type` should work though?

**Comment by stamogis** [comment]
thanks, that seems to work.

**Pull request closed without merging**
