### PR TITLE
Possibility for set a custom legend icon in layer tree

### PR DESCRIPTION
**Pull request by danceb**
I thought, it would be nice, to have the possibility to set a custom legend icon for each layer within the layer tree instead of the legend thumbnail.
So this is my attempt for realizing this.

### CODE REVIEW

**Comment by manisandro** [comment]
This functionality is provided by the `qwc-legend-service` (https://github.com/qwc-services/qwc-legend-service), would you be ok with using the service or do you still prefer it to be in the client?

**Comment by danceb** [comment]
Oh, I missed that! Of course, it is ok to use the service instead of a configuration within the client. So I will have a look at the service configuration now. Thanks for the hint!

**Comment by danceb** [comment]
Just have to ask: It seems, that the service is for a very detailed configuration for each layer within a wms service. But is it possible to just provide one icon/image and that one is used on every layer? That was the thing I was looking for. Thanks!

**Comment by manisandro** [comment]
Currently not, but should be pretty easy to implement here: https://github.com/qwc-services/qwc-legend-service/blob/master/legend_service.py#L278

**Pull request closed without merging**
