### PR TITLE
fix Consistently use theme WMS version for requests

### PR DESCRIPTION
**Pull request by luciman**
fix https://github.com/qgis/qwc2/commit/fa78ca97223f9e2d84f78d2824f9b20ae67b9ed4

otherwise all the time layer.params.VERSION will be undefined

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks, looks like I messed something up when refactoring. The idea was to use `layer.version` throughout the codebase, I've fixed this in bfdff2c2da297407e96aa409bb4b61f282fded28.

**Comment by luciman** [comment]
Yes you messed it in https://github.com/qgis/qwc2/commit/9ba5d4cb4b39dabdf2ad061097c2aa3542cb6e6c#diff-e0f25250c20937b8edc0a6ec9e5fa299


https://github.com/qgis/qwc2/commit/bfdff2c2da297407e96aa409bb4b61f282fded28 do not fix  
https://github.com/qgis/qwc2/blob/4aa77643cc226f601b47dbbda5763122aa445453/QWC2Components/utils/IdentifyUtils.js#L37

and also https://github.com/qgis/qwc2/blob/4aa77643cc226f601b47dbbda5763122aa445453/QWC2Components/plugins/DxfExport.jsx#L41 should be changed

Thank you

**Comment by manisandro** [comment]
https://github.com/qgis/qwc2/blob/4aa77643cc226f601b47dbbda5763122aa445453/QWC2Components/utils/IdentifyUtils.js#L37?

You mean the missing fallback? If yes, added in c0239b20831bf2d1f0541bc1c6afa23de3a4886c

Dxf fixed in a3bee864dfcdb30a70da9ee7a257a50662006609

(Actually I suppose we could also do away with all the fallbacks, since one could ensure that each layer in the state always has a version set)

**Comment by luciman** [comment]
No sorry I didn't seen you have added https://github.com/qgis/qwc2/blob/c0239b20831bf2d1f0541bc1c6afa23de3a4886c/QWC2Components/plugins/ThemeSwitcher.jsx#L221
in https://github.com/qgis/qwc2/commit/bfdff2c2da297407e96aa409bb4b61f282fded28

It is ok.
Thank you!

**Pull request closed without merging**
