### PR TITLE
Export heightprofile to csv

### PR DESCRIPTION
**Pull request by benoitblanc**
Hello,
I have added a button to export height profile to csv file with index, distance and elevation.

image

Thanks !

### CODE REVIEW

**Comment by benoitblanc** [comment]
ping @manisandro in case you missed it :wink:

**Comment by tpo** [comment]
Hi Benoit,

On Thu, 1 Jul 2021, Benoît Blanc wrote:

> ping @manisandro in case you missed it 😉

Sandro is on holidays this week so his answer might take some time... :-/

Greetings,
*t

**Comment by manisandro** [comment]
Thanks - would it possible to integrate it a bit more discretely into the plot area? Say a button with the export icon in the bottom right corner of the area?

**Comment by benoitblanc** [comment]
Hi,
sorry to bother you during your holidays !

I have changed the button using Icon component and export icon. It looks like something better.

image

**Comment by manisandro** [comment]
Thanks!

**Pull request merged**
