### PR TITLE
Fix plugin name in translations

### PR DESCRIPTION
**Pull request by lpinca**
Refs: https://github.com/qgis/qwc2/commit/e08aed5865534044
Refs: https://github.com/qgis/qwc2-demo-app/commit/f8e29a5126fa90d0

### CODE REVIEW

**Comment by manisandro** [comment]
`IdentifyRegion` is the correct translation key, as the tool mode is appended to the plugin name [1].

[1] https://github.com/qgis/qwc2/blob/master/components/AppMenu.jsx#L120

**Comment by lpinca** [comment]
This https://github.com/qgis/qwc2/blob/cc063c9f2f36e7c35860dfe4d84f7c813dfb5c83/components/Toolbar.jsx#L31 is currently not properly translated in `qwc2-demo-app`.

**Comment by manisandro** [comment]
Uh right - it should build the translation key the same way AppMenu does

**Comment by manisandro** [comment]
Fixed in https://github.com/qgis/qwc2/commit/47bfd1017cdc2aad659fb07c19c71d8af206bba0, thanks for reporting!

**Comment by lpinca** [comment]
@manisandro can you please take a look at https://github.com/qgis/qwc2-demo-app/pull/299?

**Pull request closed without merging**
