### PR TITLE
fix Ios mobile AppMenu Click

### PR DESCRIPTION
**Pull request by luciman**

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks - just to understand, what happens currently?

**Comment by luciman** [comment]
on iphone Safari or chrome when tap/click on burger icon for open the AppMenu, nothing happens.

**Comment by manisandro** [comment]
Uhm ok, but does `checkCloseMenu` method get called? Unless the `checkCloseMenu` is misbehaving, I wonder what killing the click event actually does?

**Comment by luciman** [comment]
I think on iphone without  ev.preventDefault(); and  ev.stopPropagation(); is like you'll click on div className="appmenu-button-container" and on div id=TopBar 
Try on desktop to click on the icon and after the menu will be opened click on TopBar blank zone (the left fone of the menu). In my opinion that is what is happening on iphone.

**Comment by luciman** [comment]
the menu will open and close immediately even with `checkCloseMenu`

**Comment by manisandro** [comment]
So for instance when clicking a submenu, can you trace who actually calls `toggleMenu`? Cause that should be the only way a menu can be closed again. It should be either because `appmenu-button-container` receives a mousedown, in which case killing the click should actually make any difference, or because `checkCloseMenu` is triggered and `!this.menuEl.contains(ev.target)` is mis-evaluated as true.

**Comment by luciman** [comment]
It is very hard for me to debug on an iphone.
The behaviour is like:
without  `onClick={this.killEvent}` in `id="AppMenu"` the menu is not opening
without `onClick={this.killEvent}` in `#AppMenu ul.appmenu-menu li`, `this.onMenuitemClicked` is not working.
what is very strange is that `this.onMenuitemClicked` is working if it is touch `#AppMenu ul.appmenu-menu li img`

**Comment by manisandro** [comment]
I'll try and find someone with such a device and see if I can investigate.

**Comment by manisandro** [comment]
So this appears to be https://github.com/facebook/react/issues/134  - ugh...

**Comment by luciman** [comment]
With that killEvent it works. I tested. I don't know if it is the best solution but it works

**Comment by manisandro** [comment]
It also works to just have an empty `onClick={ev => {}}` on `<div id="AppMenu">`. Trying to find out whether any other places are affected.

**Comment by manisandro** [comment]
I've addressed this with https://github.com/qgis/qwc2/commit/ad2f779fe4aa78ed2f08c0163b94b00508b909a0.

**Pull request closed without merging**
