### PR TITLE
Handle relative urls in themes config

### PR DESCRIPTION
**Pull request by huggla**
Fix themesConfig to work with relative urls in themesConfig.json.

### CODE REVIEW

**Comment by manisandro** [comment]
qwc2serverUrl is actually only meant to specify the optional QWC2 server-side component which does the permalink storage/resolution and possibly proxying (to avoid CORS issues). It is not the QGIS Server URL.

**Comment by huggla** [comment]
Sorry, I got a bit confused. I've updated my patch of themesConfig.js and themesConfig.py.

**Comment by manisandro** [comment]
So this basically attempts to detect the FQDN of the current machine and use that as baseurl?

Can you squash the commits as appropriate?

**Comment by huggla** [comment]
I'm having 4 weeks vacation. I'll do it when I'm back at work.

**Pull request closed without merging**
