### PR TITLE
Add sort-import ESLint rule

### PR DESCRIPTION
**Pull request by benoitblanc**
@manisandro what do you think about this configuration ?

`allowSeparatedGroups` could allow us to import style at the end of the imports.

It sorts alphabetically Capital letters, then lowercase letters.

The member syntax sort order is 
* none - import module without exported bindings.
* single - import single member.
* multiple - import multiple members.
* all - import all members provided by exported bindings.
 

It does not take into account relative or absolute imports.

For example, imports of Bookmark plugin with this rule:

```jsx
import ConfigUtils from '../utils/ConfigUtils';
import Icon from '../components/Icon';
import LocaleUtils from '../utils/LocaleUtils';
import PropTypes from 'prop-types';
import React from 'react';
import SideBar from '../components/SideBar';
import Spinner from '../components/Spinner';
import classnames from 'classnames';
import {connect} from 'react-redux';
import isEmpty from 'lodash.isempty';
import {createBookmark, getUserBookmarks, removeBookmark, updateBookmark} from '../utils/PermaLinkUtils';

import './style/Bookmark.css';
```

Thanks

### CODE REVIEW

**Comment by manisandro** [comment]
`allowSeparatedGroups` should also allow us to keep the absolute imports on top and the relative imports separately, right?

**Comment by manisandro** [comment]
This should also work right?


```jsx
import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import isEmpty from 'lodash.isempty';
import {connect} from 'react-redux';

import ConfigUtils from '../utils/ConfigUtils';
import Icon from '../components/Icon';
import LocaleUtils from '../utils/LocaleUtils';
import SideBar from '../components/SideBar';
import Spinner from '../components/Spinner';
import {createBookmark, getUserBookmarks, removeBookmark, updateBookmark} from '../utils/PermaLinkUtils';

import './style/Bookmark.css';

```

**Comment by benoitblanc** [comment]
> This should also work right?
> 
> ```js
> import PropTypes from 'prop-types';
> import React from 'react';
> import classnames from 'classnames';
> import isEmpty from 'lodash.isempty';
> import {connect} from 'react-redux';
> 
> import ConfigUtils from '../utils/ConfigUtils';
> import Icon from '../components/Icon';
> import LocaleUtils from '../utils/LocaleUtils';
> import SideBar from '../components/SideBar';
> import Spinner from '../components/Spinner';
> import {createBookmark, getUserBookmarks, removeBookmark, updateBookmark} from '../utils/PermaLinkUtils';
> 
> import './style/Bookmark.css';
> ```

No because named imports are also sorted with default imports (so `{connect}` should be before `isEmpty`). 

We would have to create one block for each of these import types:

```jsx
// absolute single default imports
import PropTypes from 'prop-types';
import React from 'react';
import classnames from 'classnames';
import isEmpty from 'lodash.isempty';
// absolute single named imports
import {connect} from 'react-redux';
// absolute multiple named imports

// relative single default imports
import ConfigUtils from '../utils/ConfigUtils';
import Icon from '../components/Icon';
import LocaleUtils from '../utils/LocaleUtils';
import SideBar from '../components/SideBar';
import Spinner from '../components/Spinner';
// relative single named imports
// relative multiple named imports
import {createBookmark, getUserBookmarks, removeBookmark, updateBookmark} from '../utils/PermaLinkUtils';

// styles
import './style/Bookmark.css';
```

**Comment by benoitblanc** [comment]
I think the last one in https://github.com/qgis/qwc2/pull/317#issuecomment-1969290080 could be a good one, I can do the changes in existing src files (in this same PR ?). We could also keep the comments for contributors to separate blocks.

What do you think ?

**Comment by manisandro** [comment]
Yes ok for me!

**Comment by benoitblanc** [comment]
As it it really laborious to change existing source code to fix errors, I think we could introduce an ESLint plugin to be able to automatically fix errors. For instance, I have found this one: https://github.com/azat-io/eslint-plugin-perfectionist where we can just introduce sort-imports rule for now https://eslint-plugin-perfectionist.azat.io/rules/sort-imports, and we could add some other rules later.

**Comment by manisandro** [comment]
Makes sense - I guess this could then be configured as a pre-commit hook

**Comment by benoitblanc** [comment]
I have added the plugin with a rule and run ESLint with `--fix` option on all the code in qwc2 to sort imports (with small fixes on indents or missing semi-column).

I think you have to run ESLint on `.eslint.js` to fix indentations directly on `master` branch because if I do it in this PR, I have conflicts between my `.eslintrc.js` and the one that is running in CI.

**Comment by manisandro** [comment]
Thanks - so this is good to merge now?

**Comment by manisandro** [comment]
Top, thanks!

**Comment by benoitblanc** [comment]
> Hmm do you still get the eslint warnings in the code editor (i.e. vscodium)?

Yes, I had to restart ESLint server

**Pull request merged**
