### PR TITLE
Refactor StandardApp component as function React component using hooks

### PR DESCRIPTION
**Pull request by benoitblanc**
Hi,

I suggest this PR to start using React function components and hooks from React >= v16.8. It could improve readibility and maintenability, and be familiar with some features of React newest versions.

Thanks

### CODE REVIEW

**Comment by manisandro** [comment]
Granted that I've so far not worked a lot with function components, personally I find them much less readable than class components. What other advantages do you see?

**Comment by benoitblanc** [comment]
I agree that readable code is subjective.

Other advantages of using function components are:
* less code
* reusable code by using functions to extract component logic
* using hooks to deal with state, or create custom hooks for your own component logic without create a class and make your component Stateful
* there can be some performance optimization to avoid DOM rendering by using specific hooks `useMemo`, `useEffect`

It is not mandatory to have all of the components as function components, we can have both of function and class components. Here is an example that could be extended in the future to other existing components or new components.

We could also use [Redux Toolkit](https://redux.js.org/introduction/why-rtk-is-redux-today) instead of `react-redux` to make store, reducers, actions easier to use but it is an other topic to enhance qwc2 app. https://redux.js.org/introduction/why-rtk-is-redux-today

**Comment by manisandro** [comment]
While I don't see any problem with starting to adopt function components in newly QWC plugins if the author wishes to use them and gradually extending them to more code if they bring a true benefit, I don't think that proactively touching existing code and risking subtle breakages is worthwhile, also considering the effort of reviewing all these changes. As far as I can see there are no indications that class components will be deprecated.

**Comment by benoitblanc** [comment]
Yep I understand your point of view about breakages and review of these changes. I close this one ;-)

**Pull request closed without merging**
