### PR TITLE
Correct translations for Catalan and Spanish

### PR DESCRIPTION
**Pull request by jblanchg**
I believe that in pull request #208 I modified older translation files.  This are the newest Catalan and Spanish files updated with the missing translations. Sorry!

### CODE REVIEW

**Comment by manisandro** [comment]
Can you please rebase to resolve the conflicts?

**Comment by jblanchg** [comment]
No conflicts now

**Comment by manisandro** [comment]
Still gives me conflicts. Please do `git pull && git rebase origin/master`

**Comment by jblanchg** [comment]
I did `git pull && git rebase origin/master` and github says that this branch has no conflicts with the base branch. I don't know what is the problem, but i'll close this pull request and open a new one with another branch. Sorry!

**Pull request closed without merging**
